// <auto-generated />
using System;
using ConsoleApp1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp1.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleApp1.Models.Dept", b =>
                {
                    b.Property<int>("Deptid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Deptid"));

                    b.Property<string>("Deptname")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.HasKey("Deptid")
                        .HasName("PK__Dept__01499C76DD2070E3");

                    b.ToTable("Dept");
                });

            modelBuilder.Entity("ConsoleApp1.Models.Emp", b =>
                {
                    b.Property<int>("Empid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Empid"));

                    b.Property<int?>("Deptid")
                        .HasColumnType("int");

                    b.Property<string>("Empname")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.HasKey("Empid")
                        .HasName("PK__Emp__AF2EBFA1A79049C9");

                    b.HasIndex("Deptid");

                    b.ToTable("Emp");
                });

            modelBuilder.Entity("ConsoleApp1.Models.Emp", b =>
                {
                    b.HasOne("ConsoleApp1.Models.Dept", "Dept")
                        .WithMany("Emps")
                        .HasForeignKey("Deptid")
                        .HasConstraintName("FK_Emp_ToTable");

                    b.Navigation("Dept");
                });

            modelBuilder.Entity("ConsoleApp1.Models.Dept", b =>
                {
                    b.Navigation("Emps");
                });
#pragma warning restore 612, 618
        }
    }
}
