// <auto-generated />
using System;
using ConsoleApp2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp2.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20240428105010_initialcreate")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleApp2.Models.Author", b =>
                {
                    b.Property<int>("Authorid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Authorid"));

                    b.Property<string>("Authorname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Authorid")
                        .HasName("PK__Author__70DDC00C8D37A21F");

                    b.ToTable("Author");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Book", b =>
                {
                    b.Property<int>("Bookid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Bookid"));

                    b.Property<int?>("Authorid")
                        .HasColumnType("int");

                    b.Property<string>("Bookname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Bookid")
                        .HasName("PK__Book__3DE1DE3F2F7462C8");

                    b.HasIndex("Authorid");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Book", b =>
                {
                    b.HasOne("ConsoleApp2.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("Authorid")
                        .HasConstraintName("FK_Book_ToTable");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
